In [2]:
import sys

In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4],dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [5]:
a= np.array([[1,2,3],
           [4,5,6]])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.shape

(2, 3)

In [8]:
a.ndim

2

In [9]:
a.size

6

In [10]:
b=np.array([
    [
    [2,3,4],
    [5,7,9],
],[
    [44,66,88],
    [42,56,77]
]
])

In [11]:
b

array([[[ 2,  3,  4],
        [ 5,  7,  9]],

       [[44, 66, 88],
        [42, 56, 77]]])

In [12]:
b.shape

(2, 2, 3)

In [13]:
b.size

12

In [7]:
z=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
z[1]

array([4, 5, 6])

In [16]:
z[0]

array([1, 2, 3])

In [17]:
z[1][0]

4

In [18]:
z[1,0]

4

In [10]:
z[1:2]

array([[4, 5, 6]])

In [14]:
z[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [21]:
z[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
z[0]=np.array([5,5,5])

In [23]:
z

array([[5, 5, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
z[1]=77

In [25]:
z

array([[ 5,  5,  5],
       [77, 77, 77],
       [ 7,  8,  9]])

In [26]:
x=np.array([1,2,3,4,5,6,7,8,9])

In [27]:
x.sum()

45

In [28]:
x.mean()

5.0

In [29]:
x.std()

2.581988897471611

In [30]:
x.var()

6.666666666666667

In [31]:
y=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [32]:
y.sum(axis=0) #column wise

array([12, 15, 18])

In [33]:
y.sum(axis=1) # row wise

array([ 6, 15, 24])

In [34]:
y.mean(axis=0)

array([4., 5., 6.])

In [35]:
a=np.arange(4)

In [36]:
a

array([0, 1, 2, 3])

In [37]:
a+10

array([10, 11, 12, 13])

In [38]:
a*10

array([ 0, 10, 20, 30])

In [39]:
a+100

array([100, 101, 102, 103])

In [40]:
l={1,2.0,2.1,3,4}

In [41]:
s=[i*10 for i in l]

In [42]:
s

[10, 20.0, 30, 40, 21.0]

In [43]:
s.sort()

In [44]:
s

[10, 20.0, 21.0, 30, 40]

In [45]:
a=np.arange(5)

In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
b=np.array([10,10,10,10,0])

In [48]:
b

array([10, 10, 10, 10,  0])

In [49]:
a+b

array([10, 11, 12, 13,  4])

In [54]:
a=np.arange(4)

In [55]:
a

array([0, 1, 2, 3])

In [57]:
a[[0,-1]]

array([0, 3])

In [58]:
a[[True,True,False,True]]

array([0, 1, 3])

In [59]:
a>=2

array([False, False,  True,  True])

In [60]:
a[a>=2]

array([2, 3])

In [61]:
a.mean()

1.5

In [69]:
a[(a==0)|(a==2)]

array([0, 2])

In [71]:
a[(a<=2) & (a%2==0)]

array([0, 2])

In [121]:
A=np.random.randint(50,size=(3,3))

In [122]:
A

array([[43, 43, 30],
       [31, 44, 33],
       [19, 11, 40]])

In [123]:
A>20

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [124]:
A[A>30]

array([43, 43, 31, 44, 33, 40])

In [125]:
A[np.array([[ True,  True, False],
       [ True, False, False],
       [False,  True,  True]])]

array([43, 43, 31, 11, 40])

In [129]:
B= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [130]:
C=np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [131]:
B.dot(C)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [132]:
#B(3x3)&C(3X2) so result matrix is (3x2) that is (row x column)

In [133]:
B@C

array([[20, 14],
       [56, 41],
       [92, 68]])

In [134]:
C.T

array([[6, 4, 2],
       [5, 3, 1]])

In [135]:
A

array([[43, 43, 30],
       [31, 44, 33],
       [19, 11, 40]])

In [137]:
B.T@C

array([[36, 24],
       [48, 33],
       [60, 42]])

In [184]:
l=list(range(5))

In [185]:
l

[0, 1, 2, 3, 4]

In [186]:
a=np.arange(5)

In [187]:
a

array([0, 1, 2, 3, 4])

In [188]:
%time np.sum(a**2)

CPU times: total: 0 ns
Wall time: 0 ns


30

In [189]:
%time sum([x**2 for x in l])

CPU times: total: 0 ns
Wall time: 0 ns


30

In [191]:
np.random.random(size=7)


array([0.54637181, 0.62280375, 0.49629878, 0.2118582 , 0.32616133,
       0.59026458, 0.80236591])

In [193]:
np.random.rand(2, 4,2)

array([[[0.10099712, 0.11011884],
        [0.84200284, 0.40956449],
        [0.19194432, 0.47181953],
        [0.87318895, 0.91128854]],

       [[0.15300165, 0.99544901],
        [0.92401207, 0.93677116],
        [0.13847785, 0.64773134],
        [0.39680408, 0.42226398]]])

In [194]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
np.arange(5, 10)


array([5, 6, 7, 8, 9])

In [196]:
np.zeros(5)

array([0., 0., 0., 0., 0.])