In [2]:
import numpy as np

In [2]:
import sys

In [9]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]


1

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [30]:
np.ones([2,2], dtype=np.int32)

array([[1, 1],
       [1, 1]])

In [36]:
np.ones([3,2], dtype=np.float64)*8.5

array([[8.5, 8.5],
       [8.5, 8.5],
       [8.5, 8.5]])

In [25]:
X = np.arange(4, dtype=np.int64)

np.ones_like(X)

array([1, 1, 1, 1], dtype=int64)

In [26]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [37]:
np.ones([4,4], dtype=np.int32) *7.5

array([[7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5]])

In [39]:
X = np.array([[2,3], [6,2]], dtype=np.int32)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [43]:
np.identity((3) ,dtype=np.int32)*9

array([[9, 0, 0],
       [0, 9, 0],
       [0, 0, 9]])

In [45]:
np.random.randint(10, size=3)

array([1, 7, 8])

In [46]:
np.random.randn(3,3,3)

array([[[ 0.28438688, -2.03716509,  0.83721645],
        [-1.84639109, -0.38312205,  0.90548447],
        [ 0.72174155,  0.30930015, -0.71413732]],

       [[-1.03489955,  0.30922543,  0.64643704],
        [-1.05031086,  0.07675911,  1.51470146],
        [-0.00901553, -0.49684573,  0.05783145]],

       [[-0.07416224,  0.26664402, -0.88625097],
        [ 0.23453933,  0.73623487, -1.02901886],
        [ 1.2132235 , -0.93896714,  0.112192  ]]])

In [47]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [21]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [11]:
np.arange(1, 61)[::-1]


array([60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44,
       43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27,
       26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,
        9,  8,  7,  6,  5,  4,  3,  2,  1])

In [55]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))


800 bytes


In [66]:
X = np.array(['A','B','C','D','E'])

X[-1]


'E'

In [67]:
X = np.array(['A','B','C','D','E'])

X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [71]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]


array([13, 14, 15, 16])

In [72]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]


1

In [73]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]


array([[ 6,  7],
       [10, 11]])

In [74]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]


array([[1, 2],
       [5, 6]])

In [75]:
X = [-5, -3, 0, 10, 40]


In [77]:
X = [-5, -3, 0, 10, 40]

X[::-1]


[40, 10, 0, -3, -5]

In [83]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[1, -3] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [84]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask


array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [85]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]


array([ 6, 10])

In [86]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]


array([ 2,  5,  6, 10])

In [97]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]


array([ 2, 10])

In [103]:
X = np.array([-1, 2, 3, -4, 5, 6, 5, 0, -9, 10])

X.all()


False

In [104]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()


True

In [105]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()


43

In [108]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) 

array([28, 32, 36, 40])

In [110]:
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) 

array([ 2.5,  6.5, 10.5, 14.5])

In [112]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 99, 9, 10])

#np.max(X)
X.max()


99